---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/images
  label: Photo
  read_only: true
- type: directory
  path: src/components
  label: Galerie
  create: documents
  match: "**/*"
  new_doc_ext: md
upload_dir: save
public_path: "/save"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
